axis_linear: 1  # Left thumb stick vertical
scale_linear: 0.5
scale_linear_turbo: 1.0

axis_angular: 3  # Right thumb stick horizontal
scale_angular: 3.0

enable_button: 10       # Left Back Top Button
enable_turbo_button: 11 # Right Back Top Button
