earth_rover_hardware:
 diagnostic_frequency: 1
 conversion_factor: 2047
 control_frequency: 12

 front_left_steering_center: 2080
 front_right_steering_center: 2200

 back_left_steering_center:   2325
 back_right_steering_center:  1996 

 front_left_steering_min: 100
 front_right_steering_min: 500

 back_left_steering_min: 600
 back_right_steering_min: 100

 front_left_steering_max: 4000
 front_right_steering_max: 4000

 back_left_steering_max: 4095
 back_right_steering_max: 4095
 
 publish_raw_feedback: false

 joints:
  # Wheel Joints
    front_left_wheel_joint        : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00203382-if02
    back_left_wheel_joint          : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00203324-if02
    front_right_wheel_joint         : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00155898-if02
    back_right_wheel_joint         : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00140203-if02

  # Ankle Joints
    front_left_steering_joint     : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00203382-if00
    back_left_steering_joint       : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00203324-if00
    front_right_steering_joint      : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00155898-if00
    back_right_steering_joint      : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00140203-if00
