earth_rover_hardware:
 conversion_factor: 1000
 joints:
  # Wheel Joints
    front_left_wheel_joint        : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00058128-if00
    front_right_wheel_joint       : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00140203-if00
    back_left_wheel_joint         : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00201225-if00
    back_right_wheel_joint        : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00203324-if00

  # Ankle Joints
  # front_left_ankle_motor

    front_left_steering_joint     : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00203338-if00
    front_right_steering_joint    : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00203356-if00
    back_left_steering_joint      : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00104525-if00
    back_right_steering_joint     : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00203390-if00

