earth_rover_hardware:
 conversion_factor: 1450
 joints:
  # Wheel Joints
    front_right_wheel_joint        : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00203356-if02
    back_left_wheel_joint       : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00104525-if02
    front_left_wheel_joint         : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00155898-if02
    back_right_wheel_joint        : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00140203-if02

  # Ankle Joints
    front_right_steering_joint     : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00203356-if00
    back_left_steering_joint    : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00104525-if00
    front_left_steering_joint      : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00155898-if00
    back_right_steering_joint     : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00140203-if00
