earth_rover_hardware:
 diagnostic_frequency: 1
 conversion_factor: 2047
 control_frequency: 10
 front_left_steering_offset: 0
 front_right_steering_offset: 0

 back_left_steering_offset: 0
 back_right_steering_offset: 0

 joints:
  # Wheel Joints
    front_left_wheel_joint        : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00203382-if02
    back_left_wheel_joint          : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00203324-if02
    front_right_wheel_joint         : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00155898-if02
    back_right_wheel_joint         : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00140203-if02

  # Ankle Joints
    front_left_steering_joint     : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00203382-if00
    back_left_steering_joint       : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00203324-if00
    front_right_steering_joint      : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00155898-if00
    back_right_steering_joint      : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00140203-if00
