earth_rover_hardware:
 diagnostic_frequency: 1
 conversion_factor: 2047
 control_frequency: 12

 front_left_steering_center: 2048
 front_right_steering_center: 2048

 back_left_steering_center:   2048
 back_right_steering_center:  2048

 front_left_steering_min: 0
 front_left_steering_max: 3000

 back_left_steering_min: 1000
 back_left_steering_max: 3000

 back_right_steering_min: 1000
 back_right_steering_max: 3000

 front_right_steering_max: 3000
 front_right_steering_min: 1000


# publish_raw_feedback: false

 publish_raw_feedback: true
 publish_feedback_rate: 10

 hardware_pwm_steering : true

 joints:
  # Wheel Joints
    front_left_wheel_joint        : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00140168-if00
    back_left_wheel_joint         : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00155898-if00
    front_right_wheel_joint       : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00203356-if00
    back_right_wheel_joint        : /dev/serial/by-id/usb-Pololu_Corporation_Pololu_Jrk_21v3_Motor_Controller_00140203-if00

  # Ankle Joints
    front_left_steering_joint     : /dev/serial/by-id/usb-Arduino__www.arduino.cc__Arduino_Mega_2560_740343130393511152C0-if00&a
    back_left_steering_joint      : /dev/serial/by-id/usb-Arduino__www.arduino.cc__Arduino_Mega_2560_740343130393511152C0-if00&b
    front_right_steering_joint    : /dev/serial/by-id/usb-Arduino__www.arduino.cc__Arduino_Mega_2560_740343130393511152C0-if00&c
    back_right_steering_joint     : /dev/serial/by-id/usb-Arduino__www.arduino.cc__Arduino_Mega_2560_740343130393511152C0-if00&d
