## Trimble NTRIP server settings

ntrip:
  user : "ROVER001:1234"
  caster: "www.vrsnow.co.uk"
  port = : 2101
  mountpoint : "15_TVN_RTCM_32"
  resend_secs: 10

  verbose: true
  lat: 51.509
  lon: -0.119
  height: 16.12

